"""
Constants for Agentic Researcher
Centralized configuration values to avoid magic numbers
"""

# Timeouts (in seconds)
DEFAULT_TIMEOUT_SECONDS = 60
HEALTH_CHECK_TIMEOUT_SECONDS = 2
HEALTH_CHECK_CONNECT_TIMEOUT_SECONDS = 1
MAX_RESEARCH_TIMEOUT_SECONDS = 300  # 5 minutes
NIM_CONNECT_TIMEOUT_SECONDS = 10
NIM_SOCK_READ_TIMEOUT_SECONDS = 60  # Increased from 30 to handle slower responses under load

# Thresholds
DEFAULT_RELEVANCE_THRESHOLD = 0.5  # Lowered from 0.7 to allow more papers through filtering
DEFAULT_SYNTHESIS_QUALITY_THRESHOLD = 0.8
MIN_RELEVANCE_THRESHOLD = 0.0
MAX_RELEVANCE_THRESHOLD = 1.0

# Limits
MAX_PAPERS_PER_QUERY = 50
MIN_PAPERS_PER_QUERY = 1
DEFAULT_MAX_PAPERS = 10
MAX_CONCURRENT_ANALYSES = 3  # Reduced from 5 to prevent NIM overload
MAX_CONCURRENT_SEARCHES = 10
MAX_QUERY_LENGTH = 500
MIN_QUERY_LENGTH = 1

# Cache TTLs (in hours/seconds)
PAPER_CACHE_TTL_HOURS = 24
SYNTHESIS_CACHE_TTL_HOURS = 24
HEALTH_CACHE_TTL_SECONDS = 30
EMBEDDING_CACHE_TTL_HOURS = 24

# Retry Configuration
MAX_RETRY_ATTEMPTS = 3
RETRY_MIN_WAIT_SECONDS = 2
RETRY_MAX_WAIT_SECONDS = 10
RETRY_MULTIPLIER = 1

# Circuit Breaker
CIRCUIT_BREAKER_FAIL_MAX = 5
CIRCUIT_BREAKER_TIMEOUT_SECONDS = 60
CIRCUIT_BREAKER_SUCCESS_THRESHOLD = 2

# Request Limits
MAX_REQUEST_SIZE_BYTES = 10 * 1024 * 1024  # 10MB
MAX_BATCH_QUERIES = 20
MAX_CONCURRENT_BATCH = 5

# Date Range
MIN_YEAR = 1900
MAX_YEAR = 2100
DEFAULT_RECENT_YEARS = 3

# Clustering
DEFAULT_CLUSTERING_EPS = 0.3
DEFAULT_CLUSTERING_MIN_SAMPLES = 3

# Synthesis
DEFAULT_SYNTHESIS_MAX_ITERATIONS = 2
DEFAULT_MAX_PAPERS_PER_SEARCH = 20

# API Configuration
DEFAULT_API_HOST = "0.0.0.0"
DEFAULT_API_PORT = 8080
DEFAULT_LOG_LEVEL = "info"

# CORS
DEFAULT_CORS_ORIGINS = ["http://localhost:8501", "http://localhost:8080"]
CORS_MAX_AGE_SECONDS = 3600

# Health Check
HEALTH_CHECK_INTERVAL_SECONDS = 30

# Metrics
METRICS_UPDATE_INTERVAL_SECONDS = 60

